version: "3"

services:
  web:
    image: python:3.10.12
    command: bash -c "pip install django && django-admin startproject myproject . && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
